import { useEffect, useState } from "react";
import jsPDF from "jspdf";

export default function Reports() {
  const [summary, setSummary] = useState(null);

  useEffect(() => {
    fetch("http://localhost:5000/report-summary")
      .then(res => res.json())
      .then(data => setSummary(data));
  }, []);

  const downloadPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("ThreatGuard - Insider Threat Report", 20, 20);

    doc.setFontSize(12);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 35);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(14);
    doc.text("Summary", 20, 52);

    doc.setFontSize(12);
    doc.text(`Total Threats Detected: ${summary.total_threats}`, 20, 65);
    doc.text(`High Severity:          ${summary.high}`, 20, 75);
    doc.text(`Medium Severity:        ${summary.medium}`, 20, 85);
    doc.text(`Low Severity:           ${summary.low}`, 20, 95);
    doc.text(`Total Financial Impact: $${summary.total_financial_impact.toLocaleString()}`, 20, 105);
    doc.text(`Most Common Threat:     ${summary.most_common_threat}`, 20, 115);
    doc.text(`False Positives:        ${summary.false_positives}`, 20, 125);

    doc.line(20, 132, 190, 132);
    doc.setFontSize(10);
    doc.text("This report is auto-generated by ThreatGuard ML System.", 20, 142);

    doc.save("ThreatGuard_Report.pdf");
  };

  const cardStyle = (color) => ({
    background: "#0f172a",
    border: `1px solid ${color}40`,
    borderRadius: 12, padding: 20,
    textAlign: "center"
  });

  return (
    <div style={{ padding: 30, color: "white", background: "#020617", minHeight: "100vh" }}>
      <h1>📄 Reports</h1>
      <p style={{ color: "#94a3b8" }}>System-generated threat analysis report</p>

      {summary && (
        <>
          {/* Summary Cards */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16, marginTop: 24 }}>
            <div style={cardStyle("#3b82f6")}>
              <div style={{ fontSize: 32, fontWeight: "bold", color: "#3b82f6" }}>{summary.total_threats}</div>
              <div style={{ color: "#94a3b8", marginTop: 4 }}>Total Threats</div>
            </div>
            <div style={cardStyle("#ef4444")}>
              <div style={{ fontSize: 32, fontWeight: "bold", color: "#ef4444" }}>{summary.high}</div>
              <div style={{ color: "#94a3b8", marginTop: 4 }}>High Severity</div>
            </div>
            <div style={cardStyle("#f97316")}>
              <div style={{ fontSize: 32, fontWeight: "bold", color: "#f97316" }}>{summary.medium}</div>
              <div style={{ color: "#94a3b8", marginTop: 4 }}>Medium Severity</div>
            </div>
            <div style={cardStyle("#22c55e")}>
              <div style={{ fontSize: 32, fontWeight: "bold", color: "#22c55e" }}>{summary.low}</div>
              <div style={{ color: "#94a3b8", marginTop: 4 }}>Low Severity</div>
            </div>
          </div>

          {/* Details */}
          <div style={{ background: "#0f172a", borderRadius: 12, padding: 24, marginTop: 20 }}>
            <h3 style={{ marginTop: 0 }}>📊 Detailed Summary</h3>
            <p>💰 Total Financial Impact: <strong style={{ color: "#ef4444" }}>${summary.total_financial_impact.toLocaleString()}</strong></p>
            <p>🎯 Most Common Threat: <strong style={{ color: "#f97316" }}>{summary.most_common_threat}</strong></p>
            <p>⚠️ False Positives: <strong>{summary.false_positives}</strong></p>
          </div>

          {/* Download Button */}
          <button onClick={downloadPDF} style={{
            marginTop: 24, padding: "14px 32px",
            background: "#3b82f6", color: "white",
            border: "none", borderRadius: 8,
            fontSize: 16, cursor: "pointer",
            fontWeight: "bold"
          }}>
            📥 Download PDF Report
          </button>
        </>
      )}
    </div>
  );
}