import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import TopFinancialImpact from "../components/charts/reports/TopFinancialImpact";
import RiskDistribution from "../components/charts/reports/RiskDistribution";

const CHART_HEIGHT = 300;

export default function Reports() {
  const [summary, setSummary]     = useState(null);
  const [chartData, setChartData] = useState(null);

  useEffect(() => {
    Promise.all([
      fetch("http://localhost:5000/report-summary").then(r => r.json()),
      fetch("http://localhost:5000/api/report-charts").then(r => r.json()),
    ]).then(([sum, charts]) => {
      setSummary(sum);
      setChartData(charts);
    });
  }, []);

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text("ThreatGuard - Insider Threat Report", 20, 20);
    doc.setFontSize(12);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 35);
    doc.line(20, 40, 190, 40);
    doc.setFontSize(14);
    doc.text("Summary", 20, 52);
    doc.setFontSize(12);
    doc.text(`Total Threats Detected: ${summary.total_threats}`, 20, 65);
    doc.text(`High Severity:          ${summary.high}`, 20, 75);
    doc.text(`Medium Severity:        ${summary.medium}`, 20, 85);
    doc.text(`Low Severity:           ${summary.low}`, 20, 95);
    doc.text(`Total Financial Impact: $${summary.total_financial_impact.toLocaleString()}`, 20, 105);
    doc.text(`Most Common Threat:     ${summary.most_common_threat}`, 20, 115);
    doc.text(`False Positives:        ${summary.false_positives}`, 20, 125);
    doc.line(20, 132, 190, 132);
    doc.setFontSize(10);
    doc.text("This report is auto-generated by ThreatGuard ML System.", 20, 142);
    doc.save("ThreatGuard_Report.pdf");
  };

  const statCards = summary ? [
    { label: "Total Threats",      value: summary.total_threats,                              color: "#3b82f6" },
    { label: "High Severity",      value: summary.high,                                       color: "#ef4444" },
    { label: "Medium Severity",    value: summary.medium,                                     color: "#f97316" },
    { label: "Low Severity",       value: summary.low,                                        color: "#22c55e" },
    { label: "Financial Impact",   value: `$${(summary.total_financial_impact/1000).toFixed(0)}k`, color: "#f59e0b" },
    { label: "False Positives",    value: summary.false_positives,                            color: "#8b5cf6" },
  ] : [];

  return (
    <div style={{
      padding: "28px 32px",
      color: "white",
      background: "#020617",
      minHeight: "100vh",
      fontFamily: "'Inter', sans-serif",
    }}>

      {/* Header */}
      <div style={{ marginBottom: 28, borderBottom: "1px solid #1e293b", paddingBottom: 18 }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <div style={{
              width: 36, height: 36, borderRadius: 8,
              background: "linear-gradient(135deg, #f59e0b, #d97706)",
              display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18
            }}>📄</div>
            <div>
              <h1 style={{ fontSize: 22, fontWeight: 700, margin: 0, letterSpacing: "-0.3px" }}>
                Reports
              </h1>
              <p style={{ fontSize: 12, color: "#64748b", margin: 0 }}>
                System-generated threat analysis — auto-updated from ML pipeline
              </p>
            </div>
          </div>

          {/* PDF Button in header */}
          {summary && (
            <button onClick={downloadPDF} style={{
              display: "flex", alignItems: "center", gap: 8,
              padding: "10px 20px",
              background: "linear-gradient(135deg, #3b82f6, #1d4ed8)",
              color: "white", border: "none", borderRadius: 10,
              fontSize: 14, fontWeight: 600, cursor: "pointer",
              letterSpacing: "0.3px",
            }}>
              📥 Download PDF
            </button>
          )}
        </div>
      </div>

      {/* Stat Cards */}
      {summary && (
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(6, 1fr)",
          gap: 12,
          marginBottom: 24,
        }}>
          {statCards.map((card, i) => (
            <div key={i} style={{
              background: "#0f172a",
              border: `1px solid ${card.color}30`,
              borderRadius: 12, padding: "14px 16px",
              position: "relative", overflow: "hidden",
            }}>
              <div style={{
                position: "absolute", top: 0, left: 0, right: 0,
                height: 3, background: card.color, borderRadius: "12px 12px 0 0"
              }} />
              <div style={{ fontSize: 26, fontWeight: 800, color: card.color, letterSpacing: "-1px", lineHeight: 1 }}>
                {card.value}
              </div>
              <div style={{ fontSize: 11, color: "#64748b", marginTop: 6, fontWeight: 500 }}>
                {card.label}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Charts Row — equal height */}
      {chartData && (
        <div style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: 16,
          marginBottom: 24,
        }}>
          <div style={{ height: CHART_HEIGHT, overflow: "hidden" }}>
            <TopFinancialImpact data={chartData.top_financial} height={CHART_HEIGHT} />
          </div>
          <div style={{ height: CHART_HEIGHT, overflow: "hidden" }}>
            <RiskDistribution data={chartData.risk_distribution} height={CHART_HEIGHT} />
          </div>
        </div>
      )}

      {/* Detailed Summary Card */}
      {summary && (
        <div style={{
          background: "#0f172a",
          border: "1px solid #1e293b",
          borderRadius: 14,
          padding: "24px 28px",
        }}>
          <div style={{ fontSize: 15, fontWeight: 600, color: "#e2e8f0", marginBottom: 16 }}>
            Detailed Summary
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 16 }}>

            {/* Total Financial Impact */}
            <div style={{
              background: "#020617", borderRadius: 10,
              padding: "16px 18px", border: "1px solid #1e293b"
            }}>
              <div style={{ fontSize: 11, color: "#475569", marginBottom: 6, letterSpacing: "0.5px" }}>
                TOTAL FINANCIAL IMPACT
              </div>
              <div style={{ fontSize: 24, fontWeight: 800, color: "#ef4444", letterSpacing: "-0.5px" }}>
                ${summary.total_financial_impact.toLocaleString()}
              </div>
              <div style={{ fontSize: 11, color: "#334155", marginTop: 4 }}>
                Cumulative exposure value
              </div>
            </div>

            {/* Most Common Threat */}
            <div style={{
              background: "#020617", borderRadius: 10,
              padding: "16px 18px", border: "1px solid #1e293b"
            }}>
              <div style={{ fontSize: 11, color: "#475569", marginBottom: 6, letterSpacing: "0.5px" }}>
                MOST COMMON THREAT
              </div>
              <div style={{ fontSize: 18, fontWeight: 700, color: "#f97316", letterSpacing: "-0.3px" }}>
                {summary.most_common_threat.replace(/_/g, " ")}
              </div>
              <div style={{ fontSize: 11, color: "#334155", marginTop: 4 }}>
                Top attack vector
              </div>
            </div>

            {/* False Positives */}
            <div style={{
              background: "#020617", borderRadius: 10,
              padding: "16px 18px", border: "1px solid #1e293b"
            }}>
              <div style={{ fontSize: 11, color: "#475569", marginBottom: 6, letterSpacing: "0.5px" }}>
                FALSE POSITIVES
              </div>
              <div style={{ fontSize: 24, fontWeight: 800, color: "#8b5cf6", letterSpacing: "-0.5px" }}>
                {summary.false_positives}
              </div>
              <div style={{
                display: "inline-block", marginTop: 6,
                background: "#8b5cf620", border: "1px solid #8b5cf640",
                borderRadius: 6, padding: "2px 10px",
                fontSize: 11, color: "#8b5cf6",
              }}>
                {((summary.false_positives / summary.total_threats) * 100).toFixed(1)}% of total
              </div>
            </div>

          </div>

          {/* Severity breakdown bar */}
          <div style={{ marginTop: 20 }}>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8, alignItems: "center" }}>
              <span style={{ fontSize: 11, color: "#475569", letterSpacing: "0.5px" }}>SEVERITY BREAKDOWN</span>
              <div style={{ display: "flex", gap: 16 }}>
                {[
                  { label: "High",   color: "#ef4444", val: summary.high },
                  { label: "Medium", color: "#f97316", val: summary.medium },
                  { label: "Low",    color: "#22c55e", val: summary.low },
                ].map((s, i) => (
                  <div key={i} style={{ display: "flex", alignItems: "center", gap: 5 }}>
                    <div style={{ width: 8, height: 8, borderRadius: "50%", background: s.color }} />
                    <span style={{ fontSize: 11, color: "#64748b" }}>{s.label}: {s.val}</span>
                  </div>
                ))}
              </div>
            </div>
            {/* Stacked bar */}
            <div style={{ display: "flex", borderRadius: 6, overflow: "hidden", height: 10 }}>
              {[
                { color: "#ef4444", pct: (summary.high   / summary.total_threats) * 100 },
                { color: "#f97316", pct: (summary.medium / summary.total_threats) * 100 },
                { color: "#22c55e", pct: (summary.low    / summary.total_threats) * 100 },
              ].map((s, i) => (
                <div key={i} style={{
                  width: `${s.pct}%`, background: s.color,
                  transition: "width 0.6s ease",
                }} />
              ))}
            </div>
          </div>
        </div>
      )}

    </div>
  );
}